[versions]
cloud = "2.1.0-SNAPSHOT"
cloudPaper = "2.0.0-SNAPSHOT"
paper = "1.21.5-R0.1-SNAPSHOT"
mccoroutine = "2.22.0"
koin = "4.0.4"
coroutine = "1.10.2"
serialization = "1.8.1"
reflect = "2.2.0"
ktor = "3.1.3"
junit = "5.12.2"
mockBukkit = "3.93.2"
commonsIo = "2.19.0"
mockk = "1.14.2"
kaml = "0.77.1"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

cloud = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloudPaper = { module = "org.incendo:cloud-paper", version.ref = "cloudPaper" }
cloud-kotlin-coroutines-annotations = { group = "org.incendo", name = "cloud-kotlin-coroutines-annotations", version.ref = "cloud" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflect" }

mccoroutine-bukkit-api = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-api", version.ref = "mccoroutine" }
mccoroutine-bukkit-core = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-core", version.ref = "mccoroutine" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version = "2.4" }

kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mock-bukkit = { group = "com.github.seeseemelk", name = "MockBukkit-v1.20", version.ref = "mockBukkit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }

koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit5 = { group = "io.insert-koin", name = "koin-test-junit5", version.ref = "koin" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.3.1" }
resource-factory = { id = "xyz.jpenilla.resource-factory", version = "1.2.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.1.20" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }

[bundles]
commands = ["cloud", "cloudPaper", "cloud-annotations", "cloud-kotlin-coroutines-annotations"]
coroutines = ["mccoroutine-bukkit-api", "mccoroutine-bukkit-core" , "kotlinx-coroutines-core"]
ktor-client = ["ktor-client-core", "ktor-client-cio", "ktor-client-mock", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"]
koin-test = ["koin-test", "koin-test-junit5"]
